name: Help
description: Ask for help with the game here.
labels: [help]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your problem here."
    validations:
      required: true